version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - habitflow
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: habit-backend:latest # Для Swarm лучше использовать готовый образ
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/habitflow
    networks:
      - habitflow
    deploy:
      [cite_start]replicas: 3 # Создаем 3 реплики бэкенда для демонстрации Swarm 
      restart_policy:
        condition: on-failure

  frontend:
    image: habit-frontend:latest
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - habitflow
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - habitflow
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - habitflow
    deploy:
      replicas: 1

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    networks:
      - habitflow
    deploy:
      mode: global # Запускает по одной копии на каждом узле кластера

volumes:
  mongo-data:
  prometheus-data:
  grafana-data:

networks:
  habitflow:
    driver: overlay # Swarm использует overlay сеть для связи между узлами